In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [10]:
lr = cross_val_score(LogisticRegression(),iris.data,iris.target)
lr

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [11]:
svc = cross_val_score(SVC(),iris.data,iris.target)
svc

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [20]:
rf = cross_val_score(RandomForestClassifier(n_estimators=30),iris.data,iris.target)
rf

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [21]:
print("Avg. Logistic Regression :",np.average(lr))
print("Avg. SVC :",np.average(svc))
print("Avg. Random Forest :",np.average(rf))

Avg. Logistic Regression : 0.9733333333333334
Avg. SVC : 0.9666666666666666
Avg. Random Forest : 0.9666666666666668
